
"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "./SessionProviderWrapper";
import { AuthProvider } from "./_auth/Provider";
import Header from "@/components/common/header";
import { Toaster } from "sonner";
import { NotificationProvider } from "@/context/NotificationContext";
import NotificationBell from "@/components/common/NotificationBell";
import { useNotification } from "@/context/NotificationContext";
import RequireRole from "@/utils/RequireRole";
import { usePathname } from "next/navigation";

function BellWrapper() {
  const ctx = useNotification();
  if (!ctx) return null;
  const { notifications, unread, setUnread } = ctx;
  return (
    <div className="fixed top-20 right-6 z-9000">
      <NotificationBell
        notifications={notifications}
        unreadCount={unread}
        onOpen={() => setUnread(0)}
      />
    </div>
  );
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/* 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const HIDE_BELL = pathname.startsWith("/auth") || pathname.startsWith("/report");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SessionProviderWrapper>
            <Toaster />
            <Header />
            <NotificationProvider>
              {!HIDE_BELL && (
                <RequireRole roles={["admin-role", "employee-role"]}>
                  <BellWrapper />
                </RequireRole>
              )}
              {children}
            </NotificationProvider>
          </SessionProviderWrapper>
        </AuthProvider>

      </body>
    </html>
  );
}
